version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-linkforge}
      POSTGRES_USER: ${POSTGRES_USER:-linkforge}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-linkforge_secure_2026}
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  backend:
    build: ./backend
    depends_on: [postgres, redis, kafka]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-linkforge}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-linkforge}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-linkforge}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: ${JWT_SECRET:-Qw7xN2pLm9KfR4tYv8Uz1Hs6Bd3Ee0AaWqPpLxM}
      APP_BASE_URL: http://localhost:8081
    ports: ["8081:8080"]

  frontend:
    build: ./frontend
    depends_on: [backend]
    environment:
      VITE_API_URL: http://localhost:8081
    ports: ["3000:80"]

volumes:
  pgdata:
