server:
  port: ${PORT:10000}
spring:
  application:
    name: linkforge
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/linkforge}
    username: ${SPRING_DATASOURCE_USERNAME:linkforge}
    password: ${SPRING_DATASOURCE_PASSWORD:linkforge}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  
app:
  base-url: ${APP_BASE_URL:http://localhost:8081}
  jwt:
    secret: ${JWT_SECRET:Qw7xN2pLm9KfR4tYv8Uz1Hs6Bd3Ee0AaWqPpLxM}
    access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}
  ratelimit:
    capacity: 60
    refill-tokens: 60
    refill-period-seconds: 60

springdoc:
  swagger-ui:
    path: /swagger-ui.html
